# Generated by Django 4.0.6 on 2022-07-26 00:04

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.core')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('genre', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Punk'), ('2', 'K-Pop'), ('3', 'Hip Hop'), ('4', 'Emo Pop')], default=None, max_length=7, null=True)),
                ('tickets', models.IntegerField()),
                ('sold_out', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
            ],
            bases=('core.core',),
        ),
    ]
